"use client";

import {
  ChevronDown,
  Copy,
  Download,
  ExternalLink,
  FileCheck,
  Link2,
} from "lucide-react";
import { useEffect, useState } from "react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import type { AgentProfile, BehaviorEvent } from "@/lib/mock/types";
import {
  confidenceFromRisk,
  humanEventKind,
  relativeTime,
  verificationHuman,
} from "@/lib/mock/narrative";
import { solanaTxUrl } from "@/lib/solana-explorer";

function RelativeTime({ ts }: { ts: number }) {
  const abs = new Intl.DateTimeFormat(undefined, {
    month: "short",
    day: "numeric",
    hour: "numeric",
    minute: "2-digit",
  }).format(new Date(ts * 1000));
  const [label, setLabel] = useState(abs);

  useEffect(() => {
    setLabel(relativeTime(ts));
    const id = window.setInterval(
      () => setLabel(relativeTime(ts)),
      60_000,
    );
    return () => window.clearInterval(id);
  }, [ts]);

  return (
    <span className="text-xs text-white/45" suppressHydrationWarning>
      {label}
    </span>
  );
}

function buildTrustReceiptText(event: BehaviorEvent, agentName: string) {
  const v = verificationHuman(event.verificationStatus);
  return [
    "AgentLedger — Trust receipt (demo)",
    "",
    `Agent: ${agentName}`,
    `Event: ${humanEventKind(event.type)}`,
    `Summary: ${event.summary}`,
    `Verification: ${v.label}`,
    `Risk score: ${event.riskScore}/100`,
    `Solana tx: ${event.anchored.solanaSignature}`,
    `Payload CID: ${event.payloadCid}`,
    `IPFS: ${event.anchored.ipfsCid}`,
    event.anchored.merkleRoot
      ? `Merkle: ${event.anchored.merkleRoot}`
      : "",
    "",
    "Generated by AgentLedger preview — not legal advice.",
  ]
    .filter(Boolean)
    .join("\n");
}

function ProofPanel({
  event,
  agentName,
}: {
  event: BehaviorEvent;
  agentName: string;
}) {
  const v = verificationHuman(event.verificationStatus);
  return (
    <div className="overflow-hidden border-t border-white/10 bg-black/20">
      <div className="space-y-4 p-5">
        <div className="flex items-start gap-2 text-sm text-white/75">
          <FileCheck className="mt-0.5 h-4 w-4 shrink-0 text-[#06B6D4]" />
          <p>
            This entry is backed by a{" "}
            <span className="text-white">tamper-proof record</span> you can
            share with legal, finance, or a partner — like a receipt, not a
            blockchain tutorial.
          </p>
        </div>
        <div className="rounded-lg border border-white/10 bg-[#0F0F1A]/80 p-4">
          <p className="text-xs font-medium uppercase tracking-wider text-white/45">
            Receipt summary
          </p>
          <ul className="mt-3 space-y-2 text-sm text-white/80">
            <li className="flex justify-between gap-4">
              <span className="text-white/50">Status</span>
              <span>{v.label}</span>
            </li>
            <li className="flex justify-between gap-4">
              <span className="text-white/50">When</span>
              <span>
                {new Intl.DateTimeFormat(undefined, {
                  dateStyle: "medium",
                  timeStyle: "short",
                }).format(new Date(event.timestampUnix * 1000))}
              </span>
            </li>
            <li className="flex justify-between gap-4">
              <span className="text-white/50">Confidence signal</span>
              <span>{confidenceFromRisk(event.riskScore).label}</span>
            </li>
          </ul>
        </div>
        <div>
          <p className="text-xs font-medium uppercase tracking-wider text-white/45">
            Technical proof (optional)
          </p>
          <p className="mt-2 text-xs text-white/45">
            For auditors or engineers. Not required to understand what happened.
          </p>
          <dl className="mt-3 space-y-3 font-mono text-[11px] text-white/70">
            <div>
              <dt className="text-white/40">Verification link</dt>
              <dd className="mt-1 break-all text-[#06B6D4]">
                {event.anchored.solanaSignature}
              </dd>
            </div>
            <div>
              <dt className="text-white/40">Record fingerprint</dt>
              <dd className="mt-1 break-all text-[#c4b5fd]">
                {event.payloadCid}
              </dd>
            </div>
            <div>
              <dt className="text-white/40">Archive copy</dt>
              <dd className="mt-1 break-all text-[#c4b5fd]">
                {event.anchored.ipfsCid}
              </dd>
            </div>
            {event.anchored.merkleRoot ? (
              <div>
                <dt className="text-white/40">Integrity check</dt>
                <dd className="mt-1 break-all">{event.anchored.merkleRoot}</dd>
              </div>
            ) : null}
          </dl>
        </div>
        <div className="flex flex-wrap gap-2">
          <Button
            type="button"
            variant="default"
            size="sm"
            className="gap-1.5 text-xs"
            onClick={() => {
              const body = buildTrustReceiptText(event, agentName);
              const blob = new Blob([body], { type: "text/plain;charset=utf-8" });
              const url = URL.createObjectURL(blob);
              const a = document.createElement("a");
              a.href = url;
              a.download = `agentledger-trust-receipt-${event.id}.txt`;
              a.click();
              URL.revokeObjectURL(url);
            }}
          >
            <Download className="h-3.5 w-3.5" />
            Download trust receipt
          </Button>
          <Button
            type="button"
            variant="outline"
            size="sm"
            className="gap-1.5 font-mono text-xs"
            onClick={() =>
              void navigator.clipboard.writeText(event.anchored.solanaSignature)
            }
          >
            <Copy className="h-3.5 w-3.5" />
            Copy verification link
          </Button>
          <Button
            type="button"
            variant="secondary"
            size="sm"
            className="gap-1.5 text-xs"
            onClick={() =>
              window.open(solanaTxUrl(event.anchored.solanaSignature), "_blank")
            }
          >
            <ExternalLink className="h-3.5 w-3.5" />
            Open in explorer
          </Button>
        </div>
      </div>
    </div>
  );
}

function DigestRow({
  event,
  agentName,
}: {
  event: BehaviorEvent;
  agentName: string;
}) {
  const [open, setOpen] = useState(false);
  const kind = humanEventKind(event.type);
  const conf = confidenceFromRisk(event.riskScore);
  const v = verificationHuman(event.verificationStatus);
  const badgeVariant =
    v.variant === "success"
      ? "success"
      : v.variant === "destructive"
        ? "destructive"
        : "secondary";

  return (
    <div className="rounded-xl border border-white/10 bg-white/[0.03]">
      <div className="flex flex-col gap-3 p-4 sm:flex-row sm:items-start sm:gap-4">
        <div className="min-w-0 flex-1 space-y-2">
          <div className="flex flex-wrap items-center gap-2">
            <RelativeTime ts={event.timestampUnix} />
            <span className="text-white/25">·</span>
            <span className="text-sm font-medium text-white">{agentName}</span>
          </div>
          <p className="text-[15px] leading-relaxed text-white/90">
            <span className="text-[#06B6D4]/80">{kind}.</span>{" "}
            {event.summary}
          </p>
          <div className="flex flex-wrap items-center gap-3 pt-1">
            <Badge variant={badgeVariant}>{v.label}</Badge>
            <button
              type="button"
              className="inline-flex items-center gap-1 text-xs text-[#c4b5fd] underline decoration-white/20 underline-offset-4 transition-colors hover:text-white hover:decoration-white/40"
              onClick={() => setOpen((o) => !o)}
            >
              <Link2 className="h-3.5 w-3.5" />
              Tamper-proof record
            </button>
          </div>
          <div className="pt-2">
            <div className="mb-1 flex justify-between text-xs text-white/45">
              <span>{conf.label}</span>
            </div>
            <div className="h-2 overflow-hidden rounded-full bg-white/10">
              <div
                className="h-full rounded-full bg-gradient-to-r from-[#7C3AED] to-[#06B6D4]"
                style={{ width: `${conf.pct}%` }}
              />
            </div>
          </div>
        </div>
        <Button
          type="button"
          variant="outline"
          size="sm"
          className="shrink-0 gap-1 self-start border-white/15 bg-white/5"
          onClick={() => setOpen((o) => !o)}
          aria-expanded={open}
        >
          View proof
          <span
            className={`inline-block transition-transform duration-200 ${open ? "rotate-180" : ""}`}
          >
            <ChevronDown className="h-4 w-4" />
          </span>
        </Button>
      </div>
      {open ? <ProofPanel event={event} agentName={agentName} /> : null}
    </div>
  );
}

export function DailyDigest({
  events,
  agents,
}: {
  events: BehaviorEvent[];
  agents: AgentProfile[];
}) {
  const sorted = [...events].sort((a, b) => b.timestampUnix - a.timestampUnix);
  const agentName = (id: string) =>
    agents.find((a) => a.id === id)?.displayName ?? "An agent";

  return (
    <section id="todays-summary" className="scroll-mt-24 space-y-2">
      <Card className="border-white/10 bg-gradient-to-br from-[#1A1A2E]/95 to-transparent">
        <CardHeader className="pb-2">
          <CardTitle className="text-lg font-semibold">
            What happened today that you should know about
          </CardTitle>
          <p className="text-sm leading-relaxed text-white/55">
            A short digest — not a log. Open{" "}
            <span className="text-white/75">View proof</span> anytime you need
            the receipt for legal, partners, or your own peace of mind.
          </p>
        </CardHeader>
        <CardContent className="space-y-3 pt-2">
          {sorted.map((event) => (
            <DigestRow
              key={event.id}
              event={event}
              agentName={agentName(event.agentId)}
            />
          ))}
        </CardContent>
      </Card>
    </section>
  );
}
